# Generated by Django 4.2.30 on 2026-05-30 05:59

from django.db import migrations, models


def migrate_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="user").update(role="reader")


def reverse_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(role="reader").update(role="user")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_roles),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("reader", "读者"), ("admin", "管理员"), ("owner", "拥有者")],
                default="reader",
                max_length=10,
                verbose_name="角色",
            ),
        ),
    ]
