# Generated by Django 4.2.30 on 2026-05-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分类名称"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="分类描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "图书分类",
                "verbose_name_plural": "图书分类",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="书名")),
                ("author", models.CharField(max_length=100, verbose_name="作者")),
                (
                    "isbn",
                    models.CharField(max_length=20, unique=True, verbose_name="ISBN"),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="出版社"
                    ),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, null=True, verbose_name="出版日期"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="简介"),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="book_covers/",
                        verbose_name="封面",
                    ),
                ),
                ("total_stock", models.IntegerField(default=0, verbose_name="总库存")),
                (
                    "current_stock",
                    models.IntegerField(default=0, verbose_name="当前库存"),
                ),
                (
                    "borrow_count",
                    models.IntegerField(default=0, verbose_name="累计借阅次数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="入库时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "图书",
                "verbose_name_plural": "图书",
                "db_table": "books",
            },
        ),
    ]
