# Generated by Django 4.2.30 on 2026-05-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="toc",
            field=models.TextField(blank=True, null=True, verbose_name="目录JSON"),
        ),
    ]
