# Generated by Django 4.2.30 on 2026-05-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_toc"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChapterContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_index", models.IntegerField(verbose_name="章节序号")),
                (
                    "chapter_title",
                    models.CharField(max_length=200, verbose_name="章节标题"),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="章节内容"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="所属图书",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节内容",
                "verbose_name_plural": "章节内容",
                "db_table": "chapter_contents",
                "ordering": ["book", "chapter_index"],
                "unique_together": {("book", "chapter_index")},
            },
        ),
    ]
