# Generated by Django 4.2.30 on 2026-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BorrowRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrow_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="借阅日期"),
                ),
                ("due_date", models.DateTimeField(verbose_name="应还日期")),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际归还日期"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrowing", "借阅中"),
                            ("returned", "已归还"),
                            ("overdue", "已逾期"),
                        ],
                        default="borrowing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "renew_count",
                    models.IntegerField(default=0, verbose_name="续借次数"),
                ),
                (
                    "fine_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="罚款金额",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="罚款是否结清"),
                ),
            ],
            options={
                "verbose_name": "借阅记录",
                "verbose_name_plural": "借阅记录",
                "db_table": "borrow_records",
            },
        ),
        migrations.CreateModel(
            name="FineRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fine_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="罚款金额"
                    ),
                ),
                (
                    "overdue_days",
                    models.IntegerField(default=0, verbose_name="逾期天数"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="是否结清"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结清时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
            ],
            options={
                "verbose_name": "罚款记录",
                "verbose_name_plural": "罚款记录",
                "db_table": "fine_records",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("borrow", "借阅"),
                            ("return", "归还"),
                            ("renew", "续借"),
                            ("create_book", "新增图书"),
                            ("edit_book", "编辑图书"),
                            ("delete_book", "删除图书"),
                            ("create_user", "新增用户"),
                            ("edit_user", "编辑用户"),
                            ("freeze_user", "冻结用户"),
                            ("unfreeze_user", "解封用户"),
                            ("pay_fine", "缴纳罚款"),
                            ("system_config", "系统设置"),
                            ("data_backup", "数据备份"),
                        ],
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "detail",
                    models.TextField(blank=True, null=True, verbose_name="操作详情"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "db_table": "operation_logs",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=50, unique=True, verbose_name="配置键"),
                ),
                ("value", models.CharField(max_length=200, verbose_name="配置值")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="配置说明"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "verbose_name_plural": "系统配置",
                "db_table": "system_configs",
            },
        ),
    ]
