# Generated by Django 4.2.30 on 2026-05-25 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("borrow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AddField(
            model_name="finerecord",
            name="borrow_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="borrow.borrowrecord",
                verbose_name="关联借阅记录",
            ),
        ),
        migrations.AddField(
            model_name="finerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="borrowrecord",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.book",
                verbose_name="图书",
            ),
        ),
        migrations.AddField(
            model_name="borrowrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="借阅用户",
            ),
        ),
    ]
