# Generated by Django 4.2.30 on 2026-05-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrow", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finerecord",
            name="fine_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="罚款金额"
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "登录"),
                    ("logout", "退出登录"),
                    ("borrow", "借阅"),
                    ("return", "归还"),
                    ("renew", "续借"),
                    ("create_book", "新增图书"),
                    ("edit_book", "编辑图书"),
                    ("delete_book", "删除图书"),
                    ("create_category", "新增分类"),
                    ("edit_category", "编辑分类"),
                    ("delete_category", "删除分类"),
                    ("create_user", "新增用户"),
                    ("edit_user", "编辑用户"),
                    ("freeze_user", "冻结用户"),
                    ("unfreeze_user", "解封用户"),
                    ("pay_fine", "缴纳罚款"),
                    ("system_config", "系统设置"),
                    ("data_backup", "数据备份"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
    ]
